### ISSUE TITLE
Install python 3.8

### ISSUE THREAD

**Issue by filias** [filias/gpwebpay#4]

**Comment by janakajanova** [comment]
I have a question. Few months ago I installed python 3.8 and after this I had a problem with Jupyter notebook(unfortunately I will need Jupyter in near future). So I downgrade Python to 3.6. Now we need 3.8, Should I download 3.8 but also keep 3.6? or I need to unninstal 3.6?

**Comment by filias** [comment]
The idea is to install 3.8 and not uninstall anything. If you are unsure about that do not install it yet.

**Comment by DanielaNy** [comment]
I installed it (ver. 3.8.2), but I do not know how to set it for virtual environment. Cannot add it as interpreter...
So all in all, I really hope I did not spoil something :fearful:  :D
