### ISSUE TITLE
Cannot change GPWEBPAY_URL configuration

### ISSUE THREAD

**Issue by johnnyunar** [filias/gpwebpay#66]
The GPWEBPAY_URL variable is now hardcoded to be pointed to the testing environment and we cannot transfer to the production environment right now. Can you please change this?

Thank you!:)

**Comment by filias** [comment]
Oh sorry for that. I will take a look later today. Thanks!

**Comment by filias** [comment]
Hey @johnunar I just released a new version which fixes that issue. 0.1.4 https://pypi.org/project/gpwebpay/0.1.4/ 
Let me know if that works for you. Thanks!

**Comment by johnnyunar** [comment]
Thank you very much! Works like charm now. 😄 🥳
